Overriding model.yaml nc=80 with nc=1
                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 270 layers, 7022326 parameters, 7022326 gradients, 15.8 GFLOPs
Transferred 342/349 items from yolov5s.pt
Scaled weight_decay = 0.0005
[34m[1moptimizer:[39m[22m SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
[34m[1mtrain: [39m[22mScanning 'C:\Users\LeeYuho\yolov5\data\labels\train\anchor_worms.cache' images and labels... 122 found, 0 missin
[34m[1mval: [39m[22mScanning 'C:\Users\LeeYuho\yolov5\data\labels\val\anchor_worms' images and labels...:   0%| | 0/7 [00:00<?, ?it/s]
[34m[1mval: [39m[22mScanning 'C:\Users\LeeYuho\yolov5\data\labels\val\anchor_worms' images and labels...7 found, 0 missing, 1 empty, 0
[34m[1mval: [39m[22mWARNING: Cache directory C:\Users\LeeYuho\yolov5\data\labels\val is not writeable: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'C:\\Users\\LeeYuho\\yolov5\\data\\labels\\val\\anchor_worms.cache.npy' -> 'C:\\Users\\LeeYuho\\yolov5\\data\\labels\\val\\anchor_worms.cache'
[34m[1mAutoAnchor: [39m[22m4.87 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to [1mruns\train\exp7
Starting training for 100 epochs...
     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/16 [00:00<?, ?it/s]                                                                                 C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
      0/99        0G    0.1199   0.01791         0        14       416:   0%|          | 0/16 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 627, in <module>
    main(opt)
  File "train.py", line 524, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 345, in train
    callbacks.run('on_train_batch_end', ni, model, imgs, targets, paths, plots, opt.sync_bn)
  File "C:\Users\LeeYuho\yolov5\utils\callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
  File "C:\Users\LeeYuho\yolov5\utils\loggers\__init__.py", line 89, in on_train_batch_end
    self.tb.add_graph(torch.jit.trace(de_parallel(model), imgs[0:1], strict=False), [])
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 741, in trace
    return trace_module(
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 983, in trace_module
    _check_trace(
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 330, in _check_trace
    check_mod = torch.jit.trace_module(
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\LeeYuho\yolov5\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\LeeYuho\yolov5\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\LeeYuho\yolov5\models\common.py", line 138, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\LeeYuho\yolov5\models\common.py", line 46, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "C:\Users\LeeYuho\anaconda3\envs\yolov5\lib\site-packages\torch\nn\functional.py", line 2282, in batch_norm
    return torch.batch_norm(
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1384448 bytes.